### ISSUE TITLE
Pheromone Trail

### ISSUE THREAD

**Issue by marcorei** [stratagems-collab/killteam-stratagem-data#13]
https://github.com/stratagems-collab/killteam-stratagem-data/blob/257aa1e7779ed2f3b600a7832f896ef88aa33b34/tyranids.json#L157

Should be:
Use this Tactic at the end of the Movement phase. Choose a model from your kill team that was set up in Reserve and set it up within 3" of a Lictor from your kill team, and more than 5" away from any enemy models.

**Comment by stratagems-collab** [comment]
Fixed in v.0.3.5-alpha
