### ISSUE TITLE
specialist tactics not showing

### ISSUE THREAD

**Issue by madjackdaw** [stratagems-collab/killteam-stratagem-data#24]
## Faction affected
all

## name of the tactic
specialist

## What is the problem?
tactics not showing except when toggle off specialist option in filter

## References on where to find the right information
.

## Expected behavior (i.e. solution)
.

## Other Comments
maybe filter gonna works too hard

**Comment by mehrmann** [comment]
Thanks for reporting. This is not a content problem though. Forwarded the issue to the app developers to check.

**Comment by marcorei** [comment]
@madjackdaw Should be fixed in 1.4.10 https://www.reddit.com/r/CompanionForKillTeam/comments/hxlqj1/1410_fixes_missing_specialist_tactics/
