### ISSUE TITLE
Avenge the fallen wrong text

### ISSUE THREAD

**Issue by JuhaniLehtimaeki** [stratagems-collab/killteam-stratagem-data#9]
## Faction affected
Custodes

## name of the tactic
Avenge the fallen

## What is the problem?
Wrong text "have the Piercing Strike's effect text"

## References on where to find the right information
Dunno, sorry!

## Expected behavior (i.e. solution)
Have right text :-)

**Comment by stratagems-collab** [comment]
Fixed in #10
